package com.myspace.ceptest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class riskResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public riskResult() {
    }




}